apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cognitive-deployment  # nombre  que tiene que tener el archivo deployment
  namespace: vallegrande
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cognitive # nombre  que tiene que estar de acuerdo al service
  template:
    metadata:
      labels:
        app: ms-cognitive # nombre  que tiene que estar de acuerdo al service
    spec:
      containers:
      - name: ms-cognitive # nombre  que tiene que estar de acuerdo al service
        image: alxander789/social:latest # nombre de tu imagen creada
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: database-config
        - secretRef:
            name: database-secrets-credentials
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-cognitive-service # nombre  que tiene que tener tu services
  namespace: vallegrande
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: ms-cognitive # nombre  que tiene que estar de acuerdo al service